[package]
name = "directory"
version = "0.1.3"
authors = ["El RIDO <elrido@gmx.net>"]
edition = "2018"

[dependencies]
diesel_migrations = "1.4.0"
dns-lookup = "1.0.1"
dotenv = "0.15.0"
hyper = "0.10.16"
maxminddb = "0.13.0"
regex = "1.3.6"
rocket = "0.4.4"

[dependencies.diesel]
version = "1.4.4"
features = ["sqlite"]

[dependencies.hyper-sync-rustls]
version = "0.3.0-rc.4"
default-features = false
features = ["client"]

[dependencies.libsqlite3-sys]
version = "0.17.1"
features = ["bundled"]

[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
features = ["diesel_sqlite_pool", "serve", "tera_templates"]

[dependencies.serde]
version = "1.0.105"
features = ["derive"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
