[package]
name = "directory"
version = "0.4.6"
authors = ["El RIDO <elrido@gmx.net>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
diesel_migrations = "1.4.0"
dns-lookup = "1.0.5"
hyper = "0.10.16"
maxminddb = "0.15.0"
regex = "1.4.1"
rocket = "0.4.5"
serde_json = "1.0.59"

[dependencies.diesel]
version = "1.4.5"
features = ["sqlite"]

[dependencies.hyper-sync-rustls]
version = "0.3.0-rc.17"
default-features = false
features = ["client"]

[dependencies.libsqlite3-sys] # included for the static binary to link it in
version = "0.18.0"
features = ["bundled"]

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["diesel_sqlite_pool", "serve", "tera_templates"]

[dependencies.serde]
version = "1.0.117"
features = ["derive"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
