[package]
name = "directory"
version = "0.1.0"
authors = ["El RIDO <elrido@gmx.net>"]
edition = "2018"

[dependencies]
rocket = "0.4.4"

[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
features = ["serve", "tera_templates"]

[dependencies.serde]
version = "1.0.105"
features = ["derive"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
