name: Rust test & lint
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install latest Rust nightly (required by Rocket)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Download GeoIP database
      run: curl -s https://download.db-ip.com/free/dbip-country-lite-2020-04.mmdb.gz | zcat > var/geoip-country.mmdb
    - name: Execute all unit and integration tests and build examples
      uses: actions-rs/cargo@v1
      env:
        GEOIP_MMDB: var/geoip-country.mmdb
        ROCKET_DATABASES: '{directory={url="var/directory.sqlite"}}'
        ROCKET_CRON_KEY: dont-use-this-in-production
      with:
        command: test
    - name: Check for common mistakes and code improvements
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
